export const quotes = [
    { index: 1, quote: "It’s okay to love something a little too much, as long as it’s real to you.", author: "MCR"},
    { index: 2, quote: "Be yourself, don’t take anything from anyone, and never let them take you alive.", author: "MCR"},
    { index: 3, quote: "Sometimes you have to kind of die inside in order to rise from your own ashes and believe in yourself and love yourself to become a new person.", author: "MCR"},
    { index: 4, quote: "So many people treat you like you’re a kid so you might as well act like one and throw your television out of the hotel window.", author: "MCR"},
    { index: 5, quote: "Never forget how beautiful you are.", author: "MCR"},
    { index: 6, quote: "Let’s have a day in the life of Gerard. Going to get coffee! Going to get coffee! That’s all it would be.", author: "MCR"},
    { index: 7, quote: "All your quirks and all your problems-even your depressions and your failures-that’s what makes you you.", author: "MCR"},
    { index: 8, quote: "Stay beautiful, keep it ugly.", author: "MCR"},
    { index: 9, quote: "Say what you want but you NEVER say it with violence!", author: "MCR"},
    { index: 10, quote: "You need just the right amount of ‘Fuck the world’ and the right amount of belief in something… and you need the right amount of love.", author: "MCR"},
    { index: 11, quote: "One day your life will flash before your eyes, make sure it’s worth watching.", author: "MCR"},
    { index: 12, quote: "Do or die, you’ll never make me, because the world will never take my heart. Go and try, you’ll never break me. ", author: "MCR"},
    { index: 13, quote: "I am living proof that no matter how bad life gets, it gets better.", author: "MCR"},
    { index: 14, quote: "If I were you I’d put that away. See you’re just wasted and thinking about the past again, darling you’ll be okay.", author: "PTV"},
    { index: 15, quote: "Give me your heart and your hand and we can run.", author: "PTV"},
    { index: 16, quote: "And I can finally see the light, oh there’s a million stars tonight. A single one could save my life.I want to hold your hand so tight, I’m gonna break my wrist.", author: "PTV"},
    { index: 17, quote: "Not all hero’s sing", author: "Tony Perry"},
    { index: 18, quote: "To live is just to fall asleep, to die is to awaken.", author: "PTV"},
    { index: 19, quote: "There is no greater vengeance than learning to enjoy again.", author: "PTV"},
    { index: 20, quote: "Life is what you make it but at least I’ve got real friends..", author: "PTV"},
    { index: 21, quote: "If you ever think about giving up, remember why you held on for so long.", author: "Haley Williams"},
    { index: 22, quote: "To anyone that ever told you you’re no good… they’re no better.", author: "Haley Williams"},
    { index: 23, quote: "The truth is, no matter what your lifestyle or occupation, nothing can really stop you when you’re allowing yourself to be exactly who you want to be.", author: "Haley Williams"},
    { index: 24, quote: "The choices that we make aren’t always perfect but it’s ok… It’s part of the journey.", author: "Haley Williams"},
    { index: 25, quote: "For me, embracing my own power is about embracing my right to be an individual.", author: "Haley Williams"},
    { index: 26, quote: "You were clearly meant for more than a life lost in the war.", author: "Glass Animals"},
    { index: 27, quote: "Guess life is long when soaked in sadness.", author: "Glass Animals"},
    { index: 28, quote: "I don’t like the terms ‘good person’ or ‘bad person’ because it is impossible to be entirely good to everyone or entirely bad to everyone.", author: "Attack on Titan"},
    { index: 29, quote: "You can’t change anything without sacrifice. I just keep moving forward.", author: "Attack on Titan"},
    { index: 30, quote: "Give up on your dreams and die.", author: "Attack on Titan"},
    { index: 31, quote: "What a beautiful day it is. It’s a shame I didn’t realize it sooner.", author: "Attack on Titan"},
    { index: 32, quote: "The world is cruel, but also beautiful.", author: "Attack on Titan"},
    { index: 33, quote: "Guess life is long when soaked in sadness.", author: "Attack on Titan"},
    { index: 34, quote: "Those who can’t abandon anything can’t change anything.", author: "Attack on Titan"},
    { index: 35, quote: "I, since the moment I was born… I’ve always been myself.", author: "Attack on Titan"},
    { index: 36, quote: "My soldiers do not buckle or yield when faced with the cruelty of this world! My soldiers push forward! My soldiers scream out! My soldiers RAAAGGEEE!", author: "Attack on Titan"},
    { index: 37, quote: "Fight to win! Risk it all for even a glimmer of real freedom! It doesn’t matter how cruel the world can be, how unjust! Fight!", author: "Attack on Titan"},
    { index: 38, quote: "Only when a person stops fighting do they lose, as long as we continue to fight, we are not beaten.", author: "Attack on Titan"},
    { index: 39, quote: "You’re gonna care what other people think and be someone you’re not your whole life? You’re fine as you are. So, talk in your own words.", author: "Attack on Titan"},
    { index: 40, quote: "We’re born free. All of us. Free. Some don’t believe it, some try to take it away. To hell with them!", author: "Attack on Titan"},
    { index: 41, quote: "Today may be the day you seize the opportunity to make your talent bloom.", author: "Haikyuu"},
    { index: 42, quote: "It’s a waste of life to be scared.", author: "Haikyuu"},
    { index: 43, quote: "Being strong means being free.", author: "Haikyuu"},
    { index: 44, quote: "Yesterday you were defeated, but what will become tomorrow?", author: "Haikyuu"},
    { index: 45, quote: "One mistake won’t kill you.", author: "Haikyuu"},
    { index: 46, quote: "It’s not ‘impossible,’ it’s just ‘hard’!", author: "Haikyuu"},
    { index: 47, quote: "It’s the process that matters. The result is really just a side-effect.", author: "Haikyuu"},
    { index: 48, quote: "Don’t you dare hang your heads! Volleyball is a sport where you always look up!", author: "Haikyuu"},
    { index: 49, quote: "To be the greatest you need to have fun, and when you’re having fun you’re the greatest.", author: "Haikyuu"},
    { index: 50, quote: "Because people don’t have wings, we find other ways to fly.", author: "Haikyuu"},
    { index: 51, quote: "He who would climb the ladder must begin at the bottom.", author: "Haikyuu"},
    { index: 52, quote: "‘Oya?’ ‘Oya Oya?’ ‘Oya Oya Oya?’", author: "Haikyuu"},
    { index: 53, quote: "Nah, I’d win.", author: "Jujutsu Kaisen"},
    { index: 54, quote: "There are only so many seats open in my life, and I don’t want to let my heart be swayed by anyone who’s not sitting in one of them. Of course, there are also people like you who bring their own seat and sit down.", author: "Jujutsu Kaisen"},
    { index: 55, quote: "I don’t know how I’ll feel when I’m dead, but I don’t want to regret the way I lived.", author: "Jujutsu Kaisen"},
    { index: 56, quote: "I’m not a hero, I’m just a Jujutsu Sorcerer.", author: "Jujutsu Kaisen"},
    { index: 57, quote: "An unfair reality is what everyone’s equally granted with.", author: "Jujutsu Kaisen"},
    { index: 58, quote: "Work is shit!", author: "Jujutsu Kaisen"},
    { index: 59, quote: "Finding more fallen hair on your pillow, watching your favorite stuffed bread disappear from convenient stores. The accumulation of those little despairs is what makes a person an adult.", author: "Jujutsu Kaisen"},
]